### ISSUE TITLE
Detailed instructions to train

### ISSUE THREAD

**Issue by zhaoxy0303** [glam-imperial/EmotionalConversionStarGAN#1]
Hi,Could you please write some detailed instructions on

1.Required datasets
2.Pre-processing data for training
3.How to train

Thanks so much.

**Comment by max-elliott** [comment]
Hi @zhaoxy0303,
Sorry its taken a little while but i've now started working on cleaning up the code so it can be easily run by others. I hope to get this done over the next few days. 
In regards to the dataset specfically, a link has now been provided in the README.

**Comment by max-elliott** [comment]
Hello again @zhaoxy0303,

The repo has been significantly updated to be much easier to train and run the model. the README has been updated with step-by-step instructions for data preprocessing, training, and conversion. A few minor changes are still to follow but everything needed to train/run the model should be done now.
