### ISSUE TITLE
num_emos should be 4 not 3

### ISSUE THREAD

**Issue by eric-zhizu** [glam-imperial/EmotionalConversionStarGAN#10]
For anyone trying to reproduce the results, edit the config files so that num_emos is 4, not 3. There are four emotions: angry, happy, sad, and neutral. Since the neutral emotion is assigned the label 3, if num_emos is 3, you will end up excluding the neutral emotion during training.

**Comment by eric-zhizu** [comment]
Also run classifier_train.py with --num_emos 4

**Comment by eric-zhizu** [comment]
Actually, the original paper used only angry, happy, and sad. Closing this issue.

**Comment by stepstep123** [comment]
> 

hello，guys. 
i am reproducting the results. but the results is not great actually. maybe we can exchange experience
